# Generated by Django 3.2.9 on 2021-11-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.BigIntegerField(blank=True, editable=False, null=True, verbose_name='Идентификатор (01)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное название')),
                ('short_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сокращенное название')),
                ('inn', models.CharField(max_length=255, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=255, verbose_name='КПП')),
            ],
            options={
                'verbose_name': 'Юр.Лицо',
                'verbose_name_plural': 'Юр.Лица',
            },
        ),
    ]
